### ISSUE TITLE
invalid method for checking capabilities

### ISSUE THREAD

**Issue by danmarsden** [SN-RECIT-formation-a-distance/moodle-local_recitdashboard#1]
https://github.com/SN-RECIT-formation-a-distance/moodle-local_recitdashboard/blob/master/src/view.php#L57

Please use has_capability or similar functions - capabilities can be overridden in many ways - you cannot query the db for this.

see:
https://moodledev.io/docs/apis/subsystems/access

this is a blocker for approval

**Comment by gustavobazzo** [comment]
Hello @danmarsden,

Thank you for your comments. 

We are wondering how can we use has_capability or similar functions when there is no associated context. In the example above, this plugin is only for teachers. How can we know that the signed user is a teacher without context or course?

**Comment by danmarsden** [comment]
I'm not convinced - in the place you use has_access, you have both course and user parameters - surely you can be using one of those to work out the correct context that should be used.

**Comment by emilevirus** [comment]
Yes, most API functions we can use it as we have courseid but what about in places we don't i.e in view.php? We'd like to check if the user is a teacher/manager in any course. If they are teacher in any course, we render our React app, otherwise we give an access denied to the user. In that specific case, we have no courseid to check the user's capability as it could be any course. What would be the best way to achieve this?

**Comment by danmarsden** [comment]
sounds like you need to rewrite what you're doing to me - it sounds problematic.

If you really can't rewrite this to use capabilities, (which I think you should be able to do) there is a user_has_role_assignment() API call so you could create a setting in your plugin that allows the admin to choose the role that should be used - (give them a list of all the site roles to choose from and select editingteacher role by default) - then check user_has_role_assignment() without passing a context.
